### ISSUE TITLE
字段与表名追加反引号应先判断参数是否已自行添加

### ISSUE THREAD

**Issue by huanmeng-qwq** [CarmJos/EasySQL#13]
### **功能简述**

字段与表名追加反引号应先判断参数是否已自行添加

### **需求来源**

表名与字段名为自定义的，可能出现配置错误导致sql语句执行报错

### **功能参考**(可选)

如果有相关功能的参考，如文本、截图，请提供给我们。

### **附加内容**

如果有什么小细节需要重点注意，请在这里告诉我们。

**Comment by Ghost-chu** [comment]
没必要，不会有人
```
.addColumn("`id`")
```
这样写代码的。
不管是用户输入，配置文件还是硬编码都不存在添加 ``` 符号的可能性。
如果用户非要输入，那也应该在交给 EasySQL 之前对数据进行核验。

**Comment by CarmJos** [comment]
我个人感觉也没有必要，本类库的目的之一就是为了能省缺大部分的 ` `` `与 ` '' `，使得代码看上去更符合Java使用者的习惯。

请问您在哪些情况下可能会有 对是否添加 `` 的误解呢？ 您的代码中那些部分经常需要手动去添加 `` 呢？可以贴一部分代码让我看看有没有必要性吗，我好做判断，谢谢！

**Comment by huanmeng-qwq** [comment]
> 我个人感觉也没有必要，本类库的目的之一就是为了能省缺大部分的 `` `` ``与 `''`，使得代码看上去更符合Java使用者的习惯。
> 
> 请问您在哪些情况下可能会有 对是否添加`` `` ``的误解呢？ 您的代码中那些部分经常需要手动去添加`` `` ``呢？可以贴一部分代码让我看看有没有必要性吗，我好做判断，谢谢！

之前使用MP的时候 有个字段想起为 `key` 但是在执行的过程中发现出现了错误 后来发现 key是一个关键词(?) 以至于之后写注解时字段名习惯添加上`` 如果不考虑添加该细节优化也许我可以尝试去一段时间去适应这种`正常`的写法 我非常喜欢这个类库<3

**Comment by CarmJos** [comment]
> > 我个人感觉也没有必要，本类库的目的之一就是为了能省缺大部分的 ` ` ``与 `''`，使得代码看上去更符合Java使用者的习惯。
> > 请问您在哪些情况下可能会有 对是否添加` ` `的误解呢？ 您的代码中那些部分经常需要手动去添加` ` `呢？可以贴一部分代码让我看看有没有必要性吗，我好做判断，谢谢！
> 
> 之前使用MP的时候 有个字段想起为 `key` 但是在执行的过程中发现出现了错误 后来发现 key是一个关键词(?) 以至于之后写注解时字段名习惯添加上`` 如果不考虑添加该细节优化也许我可以尝试去一段时间去适应这种`正常`的写法 我非常喜欢这个类库<3

我会在后续更新中添加判断，但仍然不建议自己手动加反引号哦~

**Comment by CarmJos** [comment]
见 https://github.com/CarmJos/EasySQL/releases/tag/0.3.4 。
