### ISSUE TITLE
queryValues由于存在枚举导致出现sql错误

### ISSUE THREAD

**Issue by huanmeng-qwq** [CarmJos/EasySQL#27]
### **问题简述**

用简短的话语描述一下大概问题。

### **问题来源**

描述一下通过哪些操作才发现的问题，如：

1. queryValues中存在枚举没name()

### **预期结果** (可选)

枚举应该自动toString(name)

### **问题截图/问题报错**

Caused by: java.sql.SQLException: Invalid utf8mb3 character string: 'ACED00'

### **操作环境**

- 系统环境: `Linux`
- Java版本:  `JRE8` 

### **其他补充**

如有其他补充，可以在这里描述。

**Comment by CarmJos** [comment]
这并不是bug。

通常情况下，需要自己选择采用枚举的 `toString()` 或 `name()` 方法，从而传入正确的参数。

鉴于代码误用的可能性与部分常用情况，将在下一版本中对枚举参数默认采取 `name()` 方法传入参数。

**Comment by CarmJos** [comment]
已更新~ 见 [**0.3.6**](https://github.com/CarmJos/EasySQL/releases/tag/0.3.6) 。
