### ISSUE TITLE
List类型参数传入报错

### ISSUE THREAD

**Issue by huanmeng-qwq** [CarmJos/EasySQL#38]
### **问题简述**

param为List(Collection)报错
需要toString

### **预期结果** (可选)

如果问题不发生，应该是什么情况

### **问题截图/问题报错**

java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'ranks' at row 1

### **其他补充**

https://github.com/CarmJos/EasySQL/blob/ffa0b74ccc092abd914e37e28f23161bac2d4112/easysql-impl/src/main/java/cc/carm/lib/easysql/util/StatementUtil.java#L147

**Comment by CarmJos** [comment]
非Java原始类型都应当由开发者自行序列化后存入。
