### ISSUE TITLE
查询时报错

### ISSUE THREAD

**Issue by Rockets123** [CarmJos/EasySQL#54]
### **问题简述**

使用查询报错

### **问题来源**

描述一下通过哪些操作才发现的问题，如：

1. 使用了 'createQuery'
2. 输入了 
`QueryAction queryAction = sql.createQuery()
                .inTable("player")
                .selectColumns("join")
                .addCondition("name","Bob")
                .build();`
4. 出现了报错 '[12:14:54] [SQLManager/ERROR]: #1 {SELECT `join` FROM `player` WHERE `name` = ?}'
### **操作环境**

- 系统环境: `Windows 10` / `Ubuntu` / `...`
- Java版本: `JDK11` / `OPENJDK8` / `JRE8` / `...`

**Comment by CarmJos** [comment]
1. 报错内容不全。
2. 未给出代码片段。
3. 请阅读Javafoc。

**Comment by Rockets123** [comment]
<img width="1034" alt="屏幕截图 2022-07-30 132509" src="https://user-images.githubusercontent.com/74282457/181876163-e3525476-2bb1-4c1d-8fc0-493c76f48750.png">
<img width="629" alt="屏幕截图 2022-07-30 132735" src="https://user-images.githubusercontent.com/74282457/181876183-539bbef2-5690-4751-bf02-54db2f581fd5.png">

**Comment by Rockets123** [comment]
<img width="629" alt="屏幕截图 2022-07-30 132735" src="https://user-images.githubusercontent.com/74282457/181876234-e231ac72-87
<img width="944" alt="屏幕截图 2022-07-30 132910" src="https://user-images.githubusercontent.com/74282457/181876236-ca74d18f-2969-41f1-b3ac-17407a7a0006.png">
d3-4503-8adb-306d49273c33.png">

**Comment by Rockets123** [comment]
<img width="629" alt="屏幕截图 2022-07-30 132735" src="https://user-images.githubusercontent.com/74282457/181876243-68f5798f-d1
<img width="944" alt="屏幕截图 2022-07-30 132910" src="https://user-images.githubusercontent.com/74282457/181876245-021504e7-223e-4b3f-afcd-a8db25c608f4.png">
2f-49c0-a5aa-fcfbe0dcdd7e.png">

**Comment by Rockets123** [comment]
<img width="629" alt="屏幕截图 2022-07-30 132735" src="https://user-images.githubusercontent.com/74282457/181876252-5bc4056d-4bd5-44b7-b533-f0025459affb.png">

<img width="944" alt="屏幕截图 2022-07-30 132910" src="https://user-images.githubusercontent.com/74282457/181876256-1a4f1422-b8d7-4ee6-9738-e3ad5d309f88.png">

**Comment by CarmJos** [comment]
看上去您像是不太了解MySQL。在使用查询前，您需要创建对应的表，并保障查询时的内容在表中有对应。

建议您先学习MySQL基础，再尝试使用本工具加速自己的开发吧~

**Comment by Rockets123** [comment]
可是我创建了这个表

**Comment by CarmJos** [comment]
把SQLException的内容复制一下，粘贴到百度的搜索框中，点击搜索即可。
![image](https://user-images.githubusercontent.com/36306882/181876657-51107bba-23f6-48d7-bcbd-d490100fa4cd.png)

> 另外：请在提交问题时学会先百度再提问，学会复制报错文本到问题描述(使用Markdown标注)。

**Comment by Rockets123** [comment]
解决了忘next()
